#:kivy 1.11.1

<GMWindow>:
    canvas:
        Rectangle:
            pos: self.center_x - 5, 0
            size: 10, self.height

    ScrollView:
        do_scroll_x: False
        do_scroll_y: True

        Label:
            size_hint_y: None
            height: self.texture_size[1]
            text_size: self.width, None
            padding: 10, 10
            text:
                'really some amazing text\n' * 100